plugins {
  alias(libs.plugins.android.application) apply false
  alias(libs.plugins.kotlin.android) apply false
  alias(libs.plugins.cachefix) apply false
  // NOTE do not add plugins used in *-convention.gradle here
  //   They must be added as deps to build-conventions/build.gradle!
}

def dependsOnRecursivelyByName =  { Task task, String name ->
  subprojects { project ->
    project.tasks.matching { it.name == name }.forEach { t ->
      task.dependsOn(t)
    }
  }
}

tasks.register("prePushCheck") { task ->
  group = "verification"

  dependsOnRecursivelyByName(task, "spotlessApply")
  dependsOnRecursivelyByName(task, "detektDebug")
}
