org.gradle.jvmargs=-Xmx8g -Dfile.encoding=UTF-8
kotlin.code.style=official

# Turning off unused features can spead up the build process
android.defaults.buildfeatures.aidl=false
android.defaults.buildfeatures.renderscript=false
android.defaults.buildfeatures.dataBinding=false
android.defaults.buildfeatures.shaders=false
android.nonTransitiveRClass=true
android.useAndroidX=true


org.gradle.parallel=true
org.gradle.caching=true

kapt.include.compile.classpath=false

# see https://developer.android.com/build/shrink-code#full-mode
android.enableR8.fullMode=true
