pluginManagement {
  repositories {
    google()
    mavenCentral()
    gradlePluginPortal()
  }
}
dependencyResolutionManagement {
  repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
  repositories {
    google()
    mavenCentral()
  }
}

rootProject.name = "Clarify"
includeBuild("build-conventions")
include ':lib:log:log'
include ':lib:log:android'
include ':lib:resource-refs:resource-refs'
include ':lib:resource-refs:resource-refs-compose'
include ':database'
include ':build-config'
include ':app:android'
include ':app:domain'
include ':app:routing'
include ':core:resources'
include ':core:data'
include ':core:domain'
include ':core:ui'
include ':core:routing'
include ':uikit'
include ':auth-session:data'
include ':auth-session:domain'
include ':auth-session:routing'
include ':feature:main:domain'
include ':feature:main:ui'
include ':feature:main:routing'
include ':lib:chat'
