pluginManagement {
  repositories {
    google()
    mavenCentral()
    gradlePluginPortal()
  }
}
dependencyResolutionManagement {
  repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
  repositories {
    google()
    mavenCentral()
  }
}

rootProject.name = "Clarify"
includeBuild("build-conventions")
include ':lib:log:log'
include ':lib:log:android'
include ':lib:resource-refs:resource-refs'
include ':lib:resource-refs:resource-refs-compose'
include ':lib:google:authenticator'
include ':lib:google:firestore'
include ':database'
include ':entity'
include ':uikit'
include ':build-config'
include ':app:android'
include ':app:domain'
include ':app:routing'
include ':core:resources'
include ':core:data'
include ':core:domain'
include ':core:ui'
include ':core:routing'
include ':auth-session:data'
include ':auth-session:domain'
include ':auth-session:routing'
include ':feature:profile:data'
include ':feature:profile:domain'
include ':feature:profile:ui'
include ':feature:profile:routing'
include ':feature:login:data'
include ':feature:login:domain'
include ':feature:login:routing'
include ':feature:login:ui'
include ':feature:chat-conversation:data'
include ':feature:chat-conversation:domain'
include ':feature:chat-conversation:routing'
include ':feature:chat-conversation:ui'
include ':feature:chat-direct-thread:data:common'
include ':feature:chat-direct-thread:data'
include ':feature:chat-direct-thread:domain'
include ':feature:chat-direct-thread:routing'
include ':feature:chat-direct-thread:ui'
include ':feature:chat-group-thread:data'
include ':feature:chat-group-thread:domain'
include ':feature:chat-group-thread:ui'
include ':feature:chat-group-thread:routing'
include ':feature:chat-branch:domain'
include ':feature:chat-branch:data'
include ':feature:chat-branch:ui'
include ':feature:chat-branch:routing'
include ':feature:debug-panel:data'
include ':feature:debug-panel:domain'
include ':feature:debug-panel:routing'
include ':feature:debug-panel:ui'
