plugins {
  id 'android-library-convention'
  id 'dagger-convention'
  id 'android-compose-convention'
  alias(libs.plugins.way)
}

android {
  namespace "ru.sla.clarify.feature.main.routing"
}

dependencies {
  implementation project(":core:routing")
  api project(":feature:main:domain")
  api project(":feature:main:ui")
}

