plugins {
  id 'android-library-convention'
  id 'android-compose-convention'
  id 'dagger-convention'
}

android {
  namespace "ru.sla.clarify.feature.main.ui"
}

dependencies {
  implementation project(":uikit")
  implementation project(":feature:main:domain")
  implementation libs.androidx.activity.compose // for BackHandler
}
