package ru.sla.clarify.uikit.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
data class AppColors(
  val isLight: Boolean,
  val backgroundPrimary: Color,
  val backgroundSecondary: Color,
  val backgroundTertiary: Color,
  val backgroundAccentPrimary: Color,
  val backgroundAccentSecondary: Color,
  val brandPrimary: Color,
  val brandSecondary: Color,
  val cardPrimary: Color,
  val cardSecondary: Color,
  val cardTertiary: Color,
  val cardQuaternary: Color,
  val cardQuinary: Color,
  val cardSenary: Color,
  val cardAccent: Color,
  val cardAccentSecondary: Color,
  val cardAccentVariant: Color,
  val contentPrimary: Color,
  val contentSecondary: Color,
  val contentTertiary: Color,
  val contentQuaternary: Color,
  val contentAccentPrimary: Color,
  val contentAccentSecondary: Color,
  val contentAccentTertiary: Color,
  val contentAccentVariant: Color,
  val contentAccentDark: Color,
  val contentAccentDarkSecondary: Color,
  val contentBlue: Color,
  val contentGoldPrimary: Color,
  val contentAccentReadable: Color,
  val errorPrimary: Color,
  val errorSecondary: Color,
  val successPrimary: Color,
  val successSecondary: Color,
  val buttonPrimaryBg: Color,
  val buttonPrimaryVariantBg: Color,
  val buttonPrimaryContent: Color,
  val buttonPrimaryVariantContent: Color,
  val buttonPrimaryBgDisabled: Color,
  val buttonPrimaryVariantBgDisabled: Color,
  val buttonPrimaryContentDisabled: Color,
  val buttonPrimaryVariantContentDisabled: Color,
  val buttonSecondaryBg: Color,
  val buttonSecondaryBgDisabled: Color,
  val buttonSecondaryContent: Color,
  val buttonSecondaryContentDisabled: Color,
  val buttonTertiaryContent: Color,
  val buttonTertiaryContentDisabled: Color,
  val shimmerColor: Color,
  val shimmerHighlightColor: Color,
  val graphLane1: Color,
  val graphLane2: Color,
  val graphLane3: Color,
  val graphLane4: Color,
  val graphLane5: Color,
  val graphLane6: Color,
  val graphMergeContent: Color
)
