package ru.sla.clarify.uikit.theme

import androidx.compose.runtime.staticCompositionLocalOf

enum class ColorTheme {
  Light,
  Dark
}

internal val LightColors = AppColors(
  isLight = true,
  backgroundPrimary = ColorPalette.gray0,
  backgroundSecondary = ColorPalette.gray100,
  backgroundTertiary = ColorPalette.gray1000.copy(alpha = 0.24f),
  backgroundAccentPrimary = ColorPalette.purple0,
  backgroundAccentSecondary = ColorPalette.gray550,
  brandPrimary = ColorPalette.purple150,
  brandSecondary = ColorPalette.gray450,
  cardPrimary = ColorPalette.gray0,
  cardSecondary = ColorPalette.gray100,
  cardTertiary = ColorPalette.gray0,
  cardQuaternary = ColorPalette.gray200,
  cardQuinary = ColorPalette.gray130,
  cardSenary = ColorPalette.gray115,
  cardAccent = ColorPalette.purple500,
  cardAccentSecondary = ColorPalette.gray700,
  cardAccentVariant = ColorPalette.gray0.copy(alpha = 0.20f),
  contentPrimary = ColorPalette.gray800,
  contentSecondary = ColorPalette.gray350,
  contentTertiary = ColorPalette.gray300,
  contentQuaternary = ColorPalette.gray250,
  contentAccentPrimary = ColorPalette.purple500,
  contentAccentSecondary = ColorPalette.gray0,
  contentAccentTertiary = ColorPalette.gray450,
  contentAccentVariant = ColorPalette.gray0,
  contentAccentDark = ColorPalette.gray800,
  contentAccentDarkSecondary = ColorPalette.gray1000.copy(alpha = 0.64f),
  contentBlue = ColorPalette.cyan200,
  contentGoldPrimary = ColorPalette.gold200,
  contentAccentReadable = ColorPalette.purple500,
  errorPrimary = ColorPalette.red100,
  errorSecondary = ColorPalette.red0,
  successPrimary = ColorPalette.green200,
  successSecondary = ColorPalette.green0,
  buttonPrimaryBg = ColorPalette.purple500,
  buttonPrimaryVariantBg = ColorPalette.gray550,
  buttonPrimaryContent = ColorPalette.gray0,
  buttonPrimaryVariantContent = ColorPalette.gray0,
  buttonPrimaryBgDisabled = ColorPalette.gray150,
  buttonPrimaryVariantBgDisabled = ColorPalette.gray150,
  buttonPrimaryContentDisabled = ColorPalette.gray0,
  buttonPrimaryVariantContentDisabled = ColorPalette.gray0,
  buttonSecondaryBg = ColorPalette.gray0,
  buttonSecondaryBgDisabled = ColorPalette.gray100,
  buttonSecondaryContent = ColorPalette.purple300,
  buttonSecondaryContentDisabled = ColorPalette.gray200,
  buttonTertiaryContent = ColorPalette.purple300,
  buttonTertiaryContentDisabled = ColorPalette.gray200,
  shimmerColor = ColorPalette.gray100,
  shimmerHighlightColor = ColorPalette.gray0,
  graphLane1 = ColorPalette.cyan200,
  graphLane2 = ColorPalette.blue200,
  graphLane3 = ColorPalette.teal200,
  graphLane4 = ColorPalette.magenta200,
  graphLane5 = ColorPalette.terracotta200,
  graphLane6 = ColorPalette.slate200,
  graphMergeContent = ColorPalette.gray0
)

internal val DarkColors = AppColors(
  isLight = false,
  backgroundPrimary = ColorPalette.gray550,
  backgroundSecondary = ColorPalette.gray900,
  backgroundTertiary = ColorPalette.gray1000.copy(alpha = 0.64f),
  backgroundAccentPrimary = ColorPalette.purple900,
  backgroundAccentSecondary = ColorPalette.gray0,
  brandPrimary = ColorPalette.purple150,
  brandSecondary = ColorPalette.gray0,
  cardPrimary = ColorPalette.gray500,
  cardSecondary = ColorPalette.gray450,
  cardTertiary = ColorPalette.gray550,
  cardQuaternary = ColorPalette.gray350,
  cardQuinary = ColorPalette.gray500,
  cardSenary = ColorPalette.gray550,
  cardAccent = ColorPalette.purple500,
  cardAccentSecondary = ColorPalette.gray500,
  cardAccentVariant = ColorPalette.gray0.copy(alpha = 0.20f),
  contentPrimary = ColorPalette.gray0,
  contentSecondary = ColorPalette.gray130,
  contentTertiary = ColorPalette.gray150,
  contentQuaternary = ColorPalette.gray200,
  contentAccentPrimary = ColorPalette.purple500,
  contentAccentSecondary = ColorPalette.gray0,
  contentAccentTertiary = ColorPalette.gray450,
  contentAccentVariant = ColorPalette.gray800,
  contentAccentDark = ColorPalette.gray800,
  contentAccentDarkSecondary = ColorPalette.gray1000.copy(alpha = 0.64f),
  contentBlue = ColorPalette.cyan200,
  contentGoldPrimary = ColorPalette.gold200,
  contentAccentReadable = ColorPalette.purple250,
  errorPrimary = ColorPalette.red100,
  errorSecondary = ColorPalette.red900,
  successPrimary = ColorPalette.green0,
  successSecondary = ColorPalette.green100,
  buttonPrimaryBg = ColorPalette.purple500,
  buttonPrimaryVariantBg = ColorPalette.purple500,
  buttonPrimaryContent = ColorPalette.gray0,
  buttonPrimaryVariantContent = ColorPalette.gray0,
  buttonPrimaryBgDisabled = ColorPalette.gray400,
  buttonPrimaryVariantBgDisabled = ColorPalette.gray400,
  buttonPrimaryContentDisabled = ColorPalette.gray0,
  buttonPrimaryVariantContentDisabled = ColorPalette.gray0,
  buttonSecondaryBg = ColorPalette.gray450,
  buttonSecondaryBgDisabled = ColorPalette.gray500,
  buttonSecondaryContent = ColorPalette.purple300,
  buttonSecondaryContentDisabled = ColorPalette.gray400,
  buttonTertiaryContent = ColorPalette.purple300,
  buttonTertiaryContentDisabled = ColorPalette.gray250,
  shimmerColor = ColorPalette.gray900,
  shimmerHighlightColor = ColorPalette.gray500,
  graphLane1 = ColorPalette.cyan200,
  graphLane2 = ColorPalette.blue200,
  graphLane3 = ColorPalette.teal200,
  graphLane4 = ColorPalette.magenta200,
  graphLane5 = ColorPalette.terracotta200,
  graphLane6 = ColorPalette.slate200,
  graphMergeContent = ColorPalette.gray800
)

internal val LocalAppColors = staticCompositionLocalOf<AppColors> {
  error("No AppColors provided")
}
