plugins {
  id 'android-library-convention'
  id "kotlin-inject-convention"
  id 'android-compose-convention'
  alias(libs.plugins.way)
}

android {
  namespace "ru.sla.clarify.feature.login.routing"
}

dependencies {
  implementation project(":app:domain")
  implementation project(":core:routing")
  api project(":feature:login:domain")
  api project(":feature:login:data")
  api project(":feature:login:ui")
}
