plugins {
  id 'android-library-convention'
  id 'android-compose-convention'
  id "kotlin-inject-convention"
}

android {
  namespace "ru.sla.clarify.feature.debug.panel.ui"
}

dependencies {
  implementation project(":uikit")
  implementation project(":feature:debug-panel:domain")
  implementation libs.androidx.activity.compose // for BackHandler
}
