plugins {
    id 'android-library-convention'
    id 'dagger-convention'
}

android {
    namespace "ru.sla.clarify.feature.debug.panel.domain"
}

dependencies {
  api project(":core:domain")

  implementation libs.kotlinx.serialization.json
  implementation libs.arrow.core

  ksp libs.arrow.optics.ksp
}
