plugins {
  id 'android-library-convention'
  id 'android-compose-convention'
  id 'dagger-convention'
}

android {
  namespace "ru.sla.clarify.feature.chat.direct.thread.ui"
}

dependencies {
  implementation project(":uikit")
  implementation project(":mapper:ui")
  implementation project(":feature:chat-direct-thread:domain")
  implementation project(":feature:chat-branch:domain")

  implementation libs.arrow.core
  implementation libs.androidx.activity.compose // for BackHandler

  testImplementation libs.bundles.unittest
  testRuntimeOnly libs.junit.jupiter.engine
  testRuntimeOnly libs.junit.platform.launcher
}
