plugins {
  id 'android-library-convention'
  id 'android-compose-convention'
  id 'dagger-convention'
}

android {
  namespace "ru.sla.clarify.feature.chat.group.thread.ui"
}

dependencies {
  implementation project(":uikit")
  implementation project(":mapper:ui")
  implementation project(":feature:chat-group-thread:domain")

  implementation libs.androidx.activity.compose // for BackHandler
}
