plugins {
  alias(libs.plugins.android.application)
  alias(libs.plugins.kotlin.android)
  alias(libs.plugins.spotless)
  alias(libs.plugins.detekt)
  alias(libs.plugins.cachefix)

  id "dagger-convention"
  id "android-compose-convention"
}

android {
  namespace "ru.sla.clarify.app.android"
  compileSdk 35

  defaultConfig {
    applicationId "ru.sla.clarify"
    minSdk 26
    targetSdk 34
    versionCode 1
    versionName "1.0"

    vectorDrawables {
      useSupportLibrary true
    }

    resConfigs "en", "ru"
  }

  signingConfigs {
    debug {
      storeFile file("debug.keystore")
    }

    release {
      storeFile file("upload-keystore.jks")
      storePassword System.getenv("STORE_PASSWORD")
      keyAlias System.getenv("STORE_KEY_ALIAS")
      keyPassword System.getenv("STORE_KEY_PASSWORD")
    }
  }

  buildFeatures {
    buildConfig true
  }

  buildTypes {
    debug {
      applicationIdSuffix ".dev"
      signingConfig signingConfigs.debug
      debuggable true
      minifyEnabled false
      resValue "string", "app_name", "Clarify (dev)"
    }
    internal {
      applicationIdSuffix ".internal"
      signingConfig signingConfigs.debug
      // Compose needs this to be false to be performant!
      debuggable false
      minifyEnabled true
      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
      matchingFallbacks = ['debug']
      resValue "string", "app_name", "Clarify (internal)"
    }
    release {
      minifyEnabled true
      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
      signingConfig signingConfigs.release
      resValue "string", "app_name", "Clarify"
    }
  }

  compileOptions {
    // Enable desugaring to use java datetime with minApi <26
    // https://developer.android.com/studio/write/java8-support#library-desugaring
    coreLibraryDesugaringEnabled = true

    sourceCompatibility JavaVersion.VERSION_11
    targetCompatibility JavaVersion.VERSION_11
  }

  kotlinOptions {
    jvmTarget = "11"
  }

  kotlin {
    jvmToolchain {
      languageVersion = JavaLanguageVersion.of(11)
    }
  }

  packagingOptions {
    resources {
      excludes += '/META-INF/{AL2.0,LGPL2.1}'
    }
  }
}

dependencies {
  detektPlugins(files(rootProject.file("libs/detekt-rules-1.2.0.jar")))
  detektPlugins(libs.detekt.rules.compose)

  coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.0.3")
  implementation libs.androidx.activity.compose
  implementation project(":lib:log:android")
  implementation project(":build-config")

  implementation project(":uikit")
  implementation project(":app:routing")

  implementation project(":lib:chat")
}

spotless {
  kotlin {
    target("**/*.kt")
    targetExclude("**/build/**/*.*")
    ktlint(libs.versions.ktlint.get()).editorConfigOverride(
      [
        "indent_size"    : "2",
        "max_line_length": "120",
        "disabled_rules" : "filename",
      ]
    )
    trimTrailingWhitespace()
    endWithNewline()
  }
}

detekt {
  config = files(rootProject.file("detekt-config.yml"))
  ignoredBuildTypes = [ "release" ]
}

tasks.withType(io.gitlab.arturbosch.detekt.Detekt).configureEach {
  jvmTarget = "11"
  // "exclude(**/generated/**)" doesn't work for some reason, see
  // https://github.com/detekt/detekt/issues/4127#issuecomment-1260733842
  exclude {
    // Use separator to make sure it also works on Windows
    def sep = File.separator
    it.file.absolutePath.contains("${sep}generated${sep}")
  }
  reports {
    xml.required.set(false)
    html.required.set(false)
    txt.required.set(false)
    sarif.required.set(false)
  }
}

tasks.withType(io.gitlab.arturbosch.detekt.DetektCreateBaselineTask).configureEach {
  jvmTarget = "11"
}
