plugins {
  id 'android-library-convention'
  id 'dagger-convention'
  alias(libs.plugins.sqldelight)
}

android {
  namespace "ru.sla.clarify.database"
}

sqldelight {
  databases {
    InMemoryDB {
      packageName = "ru.sla.clarify.database"
      srcDirs('src/main/sqldelight/memory')
    }
    PersistedDB {
      packageName = "ru.sla.clarify.database"
      srcDirs('src/main/sqldelight/persisted')
    }
  }
}

dependencies {
  api project(":core:domain")
  api libs.sqldelight.coroutines

  implementation project(":auth-session:domain")
  implementation libs.firebase.auth
  implementation libs.firebase.firestore
  implementation libs.sqldelight.android.driver
}
