plugins {
  id 'android-library-convention'
  id "kotlin-inject-convention"
  id 'android-compose-convention'
  alias(libs.plugins.way)
}

android {
  namespace "ru.sla.clarify.feature.debug.panel.routing"
}

dependencies {
  implementation project(":core:routing")
  api project(":feature:debug-panel:data")
  api project(":feature:debug-panel:domain")
  api project(":feature:debug-panel:ui")
}
