plugins {
  id 'android-library-convention'
  id 'android-compose-convention'
  id "kotlin-inject-convention"
}

android {
  namespace "ru.sla.clarify.feature.chat.branch.ui"
}

dependencies {
  implementation project(":uikit")
  implementation project(":mapper:ui")
  implementation project(":feature:chat-branch:domain")

  implementation libs.androidx.activity.compose // for BackHandler

  testImplementation libs.bundles.unittest
  testRuntimeOnly libs.junit.jupiter.engine
  testRuntimeOnly libs.junit.platform.launcher
}
