plugins {
  id 'android-library-convention'
  id "kotlin-inject-convention"
  id 'android-compose-convention'
  alias(libs.plugins.way)
}

android {
  namespace "ru.sla.clarify.app.routing"
}

dependencies {
  api project(":app:domain")
  api project(":core:routing")
  api project(":app:domain")
  api project(":auth-session:data")
  api project(":feature:chat-conversation:routing")
  api project(":feature:login:routing")
  api project(":lib:google:authenticator")
}
