plugins {
  id 'android-library-convention'
  id 'dagger-convention'
  id 'android-compose-convention'
  alias(libs.plugins.way)
}

android {
  namespace "ru.sla.clarify.app.routing"
}

dependencies {
  api project(":core:routing")
  api project(":auth-session:data")
  api project(":feature:main:routing")
  api project(":feature:login:routing")
}
