plugins {
  id 'android-library-convention'
  id "kotlin-inject-convention"
}

android {
  namespace "ru.sla.clarify.feature.login.data"
}

dependencies {
  implementation project(":lib:google:authenticator")
  implementation project(":chat-api")
  implementation project(":app:domain")
  implementation project(":core:domain")
  implementation project(":auth-session:data")
  implementation project(":auth-session:domain")
  implementation project(":feature:login:domain")
}
