plugins {
  id 'android-library-convention'
  id 'android-compose-convention'
  id "kotlin-inject-convention"
  alias(libs.plugins.way)
}

android {
  namespace "ru.sla.clarify.feature.chronology.routing"
}

dependencies {
  implementation project(":core:routing")
  api project(":feature:chronology:data")
  api project(":feature:chronology:domain")
  api project(":feature:chronology:ui")
  implementation project(":feature:chat-direct-thread:domain")
}
