// plugins block in groovy script doesn't support using "alias(..)"
// see https://github.com/gradle/gradle/issues/15383#issuecomment-1396061277
// but outside of plugins block everything works ok
plugins {
  id "com.google.devtools.ksp"
  id "org.jetbrains.kotlin.plugin.compose"
}

composeCompiler {
  stabilityConfigurationFiles.add(
      rootProject.layout.projectDirectory.file("compose-stability-config.conf")
  )
}

android {
  buildFeatures {
    compose true
  }

  kotlinOptions {
    freeCompilerArgs += "-opt-in=androidx.compose.animation.ExperimentalAnimationApi"
    freeCompilerArgs += "-opt-in=androidx.compose.ui.ExperimentalComposeUiApi"
    freeCompilerArgs += "-opt-in=androidx.compose.foundation.ExperimentalFoundationApi"
    freeCompilerArgs += "-opt-in=androidx.compose.foundation.layout.ExperimentalLayoutApi"
    freeCompilerArgs += "-opt-in=androidx.compose.material3.ExperimentalMaterial3Api"
    freeCompilerArgs += "-opt-in=coil.annotation.ExperimentalCoilApi"
  }
}
