// plugins block in groovy script doesn't support using "alias(..)"
// see https://github.com/gradle/gradle/issues/15383#issuecomment-1396061277
// but outside of plugins block everything works ok
plugins {
  id "com.android.library"
  id "org.jetbrains.kotlin.android"
  id "com.diffplug.spotless"
  id "io.gitlab.arturbosch.detekt"
  id "org.gradle.android.cache-fix"
}

android {
  compileSdk = 36

  defaultConfig {
    minSdk 26
  }

  buildFeatures {
    aidl = false
    renderScript = false
  }

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_11
    targetCompatibility JavaVersion.VERSION_11
  }

  kotlin {
    jvmToolchain {
      languageVersion = JavaLanguageVersion.of(11)
    }
    compilerOptions {
      jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_11
      freeCompilerArgs.add("-jvm-default=no-compatibility")
      freeCompilerArgs.add("-opt-in=kotlinx.coroutines.FlowPreview")
      freeCompilerArgs.add("-opt-in=kotlin.contracts.ExperimentalContracts")
      freeCompilerArgs.add("-opt-in=kotlinx.coroutines.ExperimentalCoroutinesApi")
    }
  }

  testOptions {
    unitTests.all {
      useJUnitPlatform()
      testLogging {
        events = ["failed", "skipped", "passed", "standard_out", "standard_error"]
        showExceptions true
        showStackTraces true
        showCauses true
        exceptionFormat "full"
      }
    }
  }
}

dependencies {
  detektPlugins(files(rootProject.file("libs/detekt-rules-1.2.0.jar")))
  detektPlugins(libs.detekt.rules.compose)
}

spotless {
  kotlin {
    target("**/*.kt")
    targetExclude("**/build/**/*.*")
    ktlint(libs.versions.ktlint.get()).editorConfigOverride(
        [
            "indent_size"                                       : "2",
            "max_line_length"                                   : "120",
            "ktlint_standard_filename"                          : "disabled",
            "ktlint_standard_function-expression-body"          : "disabled",
            "ktlint_standard_function-signature"                : "disabled",
            "ktlint_standard_class-signature"                   : "disabled",
            "ktlint_standard_blank-line-between-when-conditions": "disabled",
            "ij_kotlin_allow_trailing_comma"                    : "false",
            "ij_kotlin_allow_trailing_comma_on_call_site"       : "false",
            "ktlint_function_naming_ignore_when_annotated_with" : "Composable",
        ]
    )
    trimTrailingWhitespace()
    endWithNewline()
  }
}

detekt {
  config = files(rootProject.file("detekt-config.yml"))
  ignoredBuildTypes = ["release"]
}

tasks.withType(io.gitlab.arturbosch.detekt.Detekt).configureEach {
  jvmTarget = "11"
  // "exclude(**/generated/**)" doesn't work for some reason, see
  // https://github.com/detekt/detekt/issues/4127#issuecomment-1260733842
  exclude {
    // Use separator to make sure it also works on Windows
    def sep = File.separator
    it.file.absolutePath.contains("${sep}generated${sep}")
  }
  reports {
    xml.required.set(false)
    html.required.set(false)
    txt.required.set(false)
    sarif.required.set(false)
  }
}

tasks.withType(io.gitlab.arturbosch.detekt.DetektCreateBaselineTask).configureEach {
  jvmTarget = "11"
}
