// plugins block in groovy script doesn't support using "alias(..)"
// see https://github.com/gradle/gradle/issues/15383#issuecomment-1396061277
// but outside of plugins block everything works ok
plugins {
  id "com.google.devtools.ksp"
}

dependencies {
  implementation libs.kotlin.inject.runtime
  implementation libs.kotlin.inject.anvil.runtime
  implementation libs.kotlin.inject.anvil.runtime.optional
  ksp libs.kotlin.inject.compiler
  ksp libs.kotlin.inject.anvil.compiler
}
