plugins {
  id 'android-library-convention'
  id 'android-compose-convention'
}

android {
  namespace "ru.sla.clarify.core.ui"
}

dependencies {
  api libs.bundles.android.core
  api libs.bundles.android.ui
  api libs.amvi.viewmodel
  api libs.amvi.compose
  api libs.way

  api project(":core:domain")
  api project(":core:resources")
  api project(":lib:resource-refs:resource-refs-compose")
}
