plugins {
  id 'android-library-convention'
  id 'dagger-convention'
}

android {
  namespace "ru.sla.clarify.feature.chronology.data"
}

dependencies {
  implementation project(":database")
  implementation project(":feature:chronology:domain")
  implementation project(":feature:chat:data")
  implementation project(":feature:chat:domain")
}
