plugins {
  id "kotlin-convention"
  id "kotlin-inject-convention"
}

dependencies {
  api libs.bundles.core
  api libs.remo
  api project(":lib:log:log")
  api project(":lib:resource-refs:resource-refs")

  implementation libs.compose.runtime
  implementation libs.arrow.core

  ksp libs.arrow.optics.ksp
}
